version: '3'
services:
  redis:
    image: "redis:5-alpine"
    ports:
     - "127.0.0.1:6379:6379"
  mysql:
    image: "mysql:5"
    volumes:
     - ./initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: {{name}}
      MYSQL_ROOT_PASSWORD: example
    ports:
     - "127.0.0.1:3306:3306"
  rabbitmq:
    image: "rabbitmq:3-alpine"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
    - "127.0.0.1:15672:15672"
    - "127.0.0.1:4369:4369"
    - "127.0.0.1:5672:5672"
    - "127.0.0.1:25672:25672"  
