version: '3'
  redis:
    image: "redis:5-alpine"
    ports:
     - "127.0.0.1:6379:6379"
  mysql:
    image: "mysql:5"
    volumes:
     - ../initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: {{name}}
      MYSQL_ROOT_PASSWORD: example
    ports:
     - "127.0.0.1:3306:3306"
